#!/bin/bash

function count_args ()
{
  cat <<COUNTS

count_args('heroku config #-a', 'config', dryrun)  # argc => $#

  ## With Quotes
  [ "\$@" ] $( i=1; for a in "$@"
    do
      printf "(${i} =>) ${a} "
      i=$(( $i + 1 ))
    done
  )
  [ "\$*" ] $( i=1; for a in "$*"
    do
      printf "(${i} =>) ${a} "
      i=$(( $i + 1 ))
    done
  )

  ## Without Quotes
  [ \$@ ] $( i=1; for a in $@
    do
      printf "(${i} =>) ${a} "
      i=$(( $i + 1 ))
    done
  )
  [ \$* ] $( i=1; for a in $*
    do
      printf "(${i} =>) ${a} "
      i=$(( $i + 1 ))
    done
  )

COUNTS
}

count_args 'heroku config #-a' 'config' dryrun

function function_arg_passing_one() {
  cat <<DIAG
WAYS TO PASS ARGS FROM 1 FUNCTION TO ANOTHER:

function_arg_passing_one(one, 'two with spaces', three, 'four with spaces')
  (# =>) $# (1 =>) $1 (2 =>) $2 (3 =>) $3 (4 =>) $4

  function_arg_passing_two("\$@")  ## IDEAL METHOD
    $(function_arg_passing_two "$@")

  function_arg_passing_two(\$*)
    $(function_arg_passing_two $*)

DIAG
}

function function_arg_passing_two() {
cat <<<"(# =>) ${#@} (1 =>) $1 (2 =>) $2 (3 =>) $3 (4 =>) $4"
}
function_arg_passing_one one 'two with spaces' three 'four with spaces'

function shift_args() {
  cat <<DIAG
shift_args(-n, two, three, four)
  (@ =>) $@ (# =>) $# (1 =>) $1 (2 =>) $2 (3 =>) $3

    shifting...

DIAG

  first="$1"
  shift

  cat <<DIAG
  (@ =>) $@ (# =>) $# (1 =>) $1 (2 =>) $2 (3 =>) $3

    first => '$first'  ## backup from before calling shift
DIAG
}
shift_args -n two three four

