#!/bin/bash

function manga_style() {
  cat <<STYLE
    <style type="text/css">
      img {
        width: 90%;
        margin: 10px;
        text-align: center;
      }
      h1 {
        font-size: 144pt;
        border: dashed 2px red;
        color: black;
      }
    </style>
STYLE
}

function prev_link() {
  printf '<a href="%s.html">&lt; Prev</a>' "$1"
}

function next_link() {
  printf ' ... <a href="%s.html">Next &gt;</a>' "$1"
}

function add_to_toc() {
  printf '<a href="%s.html">%s</a><br/>' "$1" "$1"
}

function heading() {
  hr_tag
  echo "<h1>$1</h1>"
}

function img_tags() {
  for b in "${1}/"*
  do
    printf '<img src="%s" />' "$b"
  done
}

function hr_tag() {
  echo "<hr />"
}


function manga_template() {
  cat <<TEMPLATE
<html>
  <head>
    <style type="text/css">
    img {
      width: 90%;
      margin: 10px;
      text-align: center;
    }
    h1 {
      font-size: 144pt;
      border: dashed 2px red;
      color: black;
    }
    </style>

    <script src="file:///var/www/public/js/jquery.min.js" ></script>
    <script type="text/javascript">
      function jumpto(img) {
        window.location = [window.location.pathname, \$(img).val()].join('#');
      }
    </script>
  </head>
  <body>
    ${prev_link}
    <hr />

    <h1>${chapter_number}</h1>

    <select onchange="jumpto(this);">
      ${img_options}
    </select>

    <hr/>

    ${img_tags}

    <hr />

    ${prev_link} ... ${next_link}
</body>
</html>
TEMPLATE
}

function img_tag() {
  cat <<IMG
  <img id="${number}" title="${number}" src="${filename}" />
IMG
}


i="index"
p="$i"

for z in 1
do
  manga_style >"${i}.html"

  for c in */
  do
    a="${c%/}"
    ih="${i}.html"
    ph="${p}.html"
    ah="${a}.html"

    if [[ "$ph" != "$ih" ]]; then
      next_link "$a" >>"$ph"
    fi

    add_to_toc "$a" >>"$ih"

    # Work on Current File
    manga_style >"$ah"
    prev_link "$p" >>"$ah"
    hr_tag >>"$ah"
    heading "$a" >>"$ah"
    img_tags "$a" >>"$ah"
    hr_tag >>"$ah"
    prev_link "$p" >>"$ah"
    p="$a"
  done
done
