#!/bin/bash

function manga_style() {
  cat <<STYLE
    <style type="text/css">
      img {
        width: 90%;
        margin: 10px;
        text-align: center;
      }
      h1 {
        font-size: 144pt;
        border: dashed 2px red;
        color: black;
      }
    </style>
STYLE
}

function prev_link() {
  printf '<a href="%s.html">&lt; Prev</a>' "$1"
}

function next_link() {
  printf '<a href="%s.html">Next &gt;</a>' "$1"
}

function add_to_toc() {
  printf '<a href="%s.html">%s</a><br/>' "$1" "$1"
}

function heading() {
  echo "<hr />"
  echo "<h1>$1</h1>"
}

function img_tags() {
  for b in "${1}/"*
  do
    printf '<img src="%s" />' "$b"
  done
}

function hr_tag() {
  echo "<hr />"
}

i="index"
p="$i"

for z in 1
do
  manga_style >$i

  for a in *
  do
    ih="${i}.html"
    ph="${p}.html"
    ah="${a}.html"

    if [[ "$ph" != "$ih" ]]; then
      next_link "$a" >>"$ph"
    fi

    add_to_toc "$a" >>"$ih"

    # Work on Current File
    manga_style >"$ah"
    prev_link "$p" >>"$ah"
    hr_tag >>"$ah"
    heading "$a" >>"$ah"
    img_tags "$a" >>"$ah"
    hr_tag >>"$ah"
    prev_link "$p" >>"$ah"
    p="$a"
  done
done
