#!/bin/bash

cat <<"METADATA" >/dev/null
  NAME: unwatched_episodes
  DESCRIPTION:
    Go through all anime folders and list episodes that haven't been watched
  according to watched.grep.

  AUTHOR: Joshua Toyota
  DATE: 2013-09-08 19:32:19

METADATA

watched_file="watched.grep"
global_watched_file="$HOME/Desktop/Anime/global.watched.grep"

start_dir="$(pwd)"
unwatched_dir="$HOME/Desktop/Anime"

[[ -n "$1" ]] && unwatched_dir="$1"

cd $unwatched_dir

echo
find . -iname $watched_file | grep -v '^..watched.grep$' | while read wf
do
  d="$(dirname "$wf")"
  lines="$(find "$d" -type f | grep -vf "$wf" -f "$global_watched_file" 2>/dev/null)"

  if [[ -n "$lines" ]]; then
    echo "$lines"
    echo
  fi
done | less

cd "$start_dir"

